name: Nodity
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.3
  cloud_firestore: ^5.6.4

  pointycastle: ^3.6.1
  convert: ^3.1.1
  crypto: ^3.0.2
  asn1lib: ^1.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/images/

  fonts:
   - family: Hallasan
     fonts:
       - asset: lib/assets/fonts/JejuHallasan.ttf
   - family: Gothic
     fonts:
       - asset: lib/assets/fonts/JejuGothic.ttf
   - family: Jersey25
     fonts:
       - asset: lib/assets/fonts/Jersey25.ttf

