// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0Avcss2_c1f1Nt3ot8rRnFE5nodLh50',
    appId: '1:891838999884:web:552920d24516e12729b3e9',
    messagingSenderId: '891838999884',
    projectId: 'thesis-af99a',
    authDomain: 'thesis-af99a.firebaseapp.com',
    storageBucket: 'thesis-af99a.firebasestorage.app',
    measurementId: 'G-G15TBW22X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpoUar0DCi7jgCcwTb4mYRMVYE29a6dfc',
    appId: '1:891838999884:android:4a2cf2364a4ae38329b3e9',
    messagingSenderId: '891838999884',
    projectId: 'thesis-af99a',
    storageBucket: 'thesis-af99a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg8j-aFoEbaNGTScqbW14K2NSu3tNOawo',
    appId: '1:891838999884:ios:9dc399f4297dbe7c29b3e9',
    messagingSenderId: '891838999884',
    projectId: 'thesis-af99a',
    storageBucket: 'thesis-af99a.firebasestorage.app',
    iosBundleId: 'com.example.preThesisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg8j-aFoEbaNGTScqbW14K2NSu3tNOawo',
    appId: '1:891838999884:ios:9dc399f4297dbe7c29b3e9',
    messagingSenderId: '891838999884',
    projectId: 'thesis-af99a',
    storageBucket: 'thesis-af99a.firebasestorage.app',
    iosBundleId: 'com.example.preThesisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm0Avcss2_c1f1Nt3ot8rRnFE5nodLh50',
    appId: '1:891838999884:web:91bcbd94b143c6f629b3e9',
    messagingSenderId: '891838999884',
    projectId: 'thesis-af99a',
    authDomain: 'thesis-af99a.firebaseapp.com',
    storageBucket: 'thesis-af99a.firebasestorage.app',
    measurementId: 'G-CG7EN48DD2',
  );
}
